autonomys/auto-sdk

- packages/auto-utils/package.json
- packages/auto-utils/src/index.ts
- packages/auto-utils/src/save.ts
- yarn.lock
- Add a generic dynamic save function that both support local storage or file system (use the key as the fileName + extension in the case of a file system
> Add dynamic save for both client and node

- .gitignore
- README.md
- packages/auto-utils/__test__/network.test.ts
- packages/auto-utils/src/constants/network.ts
- scripts/localhost-run-test.sh
- scripts/localhost.sh
Hopefully, this will make the development easier, especially as we start tackling extrinsics
To test the packages against a local node, you can use the script at `scripts/localhost.sh`.
1. Verify that the line 3-7 of the script matches your current OS and architecture.
```bash
OS="macos" # macos | ubuntu | windows
ARCHITECTURE="aarch64" # aarch64 | x86_64-skylake | x86_64-v2
```
2. Run the script:
```bash
./scripts/localhost.sh
```
This script will download the latest version of the node and farmer for your OS and architecture, start the node, and farmer
3. Run the tests:
```bash
bash scripts/localhost-run-test.sh
```
The tests will detect the local node and farmer and run the tests against them instead of the public testnet.
> Add a scripts folder in root with bash script that can run a local testnet

- README.md
- scripts/download.sh
- scripts/run-dev.js
- scripts/run-farmer.sh
- scripts/run-node.sh
- scripts/run-operator.sh
Now there is 3 bash scripts and 1 js script that act as the main entrypoint
`node scripts/run-dev.js` will:
- Download the latest version of the node and farmer for your OS and architecture (`scripts/download.sh`);
- Start the node, create and insert the keystore in the node (`scripts/run-node.sh`);
- Start the farmer (`scripts/run-farmer.sh`);
- Register the node as operator, wait and kill the node and farmer (inside `scripts/run-dev.js`);
- Start the node as an operator (`scripts/run-operator.sh`);
- Restart the farmer (`scripts/run-farmer.sh`).
> Improve the localhost script to also run a operator

- .vscode/auto.code-workspace
- examples/node/.env.local
- examples/node/README.md
- examples/node/package.json
- examples/node/src/address.ts
- examples/node/src/balance.ts
- examples/node/src/transfer.ts
- examples/node/src/utils/setup.ts
- package.json
- yarn.lock
Simple list of scripts to query data and execute extrinsics:
```bash
yarn
```
```bash
yarn balance
```
```bash
yarn transfer
```
```bash
yarn address
```
```bash
yarn all
```
> Create reusable scripts to query balance and transfer tokens

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Bumped the version of the Auto-SDK packages from 0.3.0 to 0.4.0.
- Updated the `@autonomys/auto-utils` dependency to version ^0.4.0 across multiple packages.
- Updated `gitHead` to reflect the new commit hash in all package.json files.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Bump Lerna version to 0.4.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.3.0 to 0.4.0.
</details>
</td>
<td><a …
> Auto-SDK Version Pumped To 0.4.0

- packages/auto-drive/src/metadata/offchain/folder.ts
bug_fix
___
- Fixed an issue where the folder name was missing in the `OffchainFolderMetadata` by adding an optional `name` parameter to the `folderMetadata` function.
- Updated the `folderMetadata` function to include the `name` in the returned metadata object.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>folder.ts</strong><dd><code>Add optional folder name to metadata function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-drive/src/metadata/offchain/folder.ts
<li>Added an optional <code>name</code> parameter to the <code>folderMetadata</code> function.<br> <li> Included …
> Fixed missing folder name in metadata

- packages/auto-drive/src/metadata/offchain/file.ts
Bug fix
___
- Fixed the file chunks list creation by filtering nodes to include only those with decodable data.
- Corrected the `totalChunks` calculation to reflect the actual number of valid chunks.
- Updated the `chunks` array to map only the filtered nodes, ensuring accurate metadata.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>file.ts</strong><dd><code>Fix and optimize file chunks list creation logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-drive/src/metadata/offchain/file.ts
<li>Added imports for <code>IPLDNodeData</code> and <code>MetadataType</code>.<br> <li> Filtered nodes to include only …
> Fix file chunks list creation

- packages/auto-consensus/src/info.ts
spacePledge was returning bigint | number, making it harder to use, now returning only bigint
___
enhancement, bug fix
___
- Changed the return type of the `spacePledge` function to `Promise<bigint>`, ensuring consistency and ease of use.
- Updated the `shouldAdjustSolutionRange` function to explicitly return a `Promise<boolean>`.
- Modified the `maxPiecesInSector` function to return a `bigint` instead of a number.
- Ensured the `blockchainSize` function returns a `Promise<bigint>`, aligning with the new standard.
___
<tr>
<td>
<details>
<summary><strong>info.ts</strong><dd><code>Standardize return types for consistency and clarity</code>&nbsp; &nbsp; …
> Fix spacePledge return type

- packages/auto-consensus/src/account.ts
- packages/auto-consensus/src/types/account.ts
- packages/auto-consensus/src/utils/parse.ts
Nonce was returning a BN, I parse it to bigint and made a parseBN function
___
Bug fix, Enhancement
___
- Fixed the type of `nonce` in account by parsing it to `bigint` using a new `parseBN` function.
- Updated the `AccountData` type to reflect the change from `BN` to `bigint` for `nonce`.
- Enhanced the `parseBalance` function to utilize the new `parseBN` function for consistency.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>account.ts</strong><dd><code>Fix nonce type by parsing with parseBN</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Fix type of nonce in account

- packages/auto-consensus/src/info.ts
Change logic to reproduce these changes https://github.com/autonomys/subspace/pull/3086
___
enhancement
___
- Refactored the space pledge logic to calculate the number of pieces instead of sectors.
- Renamed the function `solutionRangeToSectors` to `solutionRangeToPieces` and updated its logic.
- Removed the `piecesInSector` parameter from the function as it is no longer needed.
- Updated the `spacePledge` function to use the new `solutionRangeToPieces` logic.
___
<tr>
<td>
<details>
<summary><strong>info.ts</strong><dd><code>Refactor space pledge logic to calculate pieces instead of sectors</code></dd></summary>
<hr>
packages/auto-consensus/src/info.ts …
> Update space pledge logic

- packages/auto-consensus/src/info.ts
___
enhancement, documentation
___
- Renamed the `spacePledge` function to `spacePledged` to correct a typo.
- Introduced a deprecated wrapper for the old `spacePledge` function to maintain backward compatibility.
- Added comments to indicate that `spacePledge` is deprecated and will be removed in a future release.
___
<tr>
<td>
<details>
<summary><strong>info.ts</strong><dd><code>Rename and deprecate `spacePledge` function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-consensus/src/info.ts
<li>Renamed <code>spacePledge</code> function to …
> Fix spacePledge typo -> spacePledged

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
- I had change the rpc url of taurus for the foundation one, but did not re build the projects, so the publish 0.7.0 has a bad url
___
enhancement
___
- Updated the version across multiple packages from 0.7.0 to 0.7.1.
- Updated the dependency `@autonomys/auto-utils` to version ^0.7.1 in several packages.
- These changes ensure that the correct RPC URL is used and the packages are correctly rebuilt and published.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Fix taurus url and publish 0.7.1

- packages/auto-utils/src/constants/network.ts
- Use Autonomys labs rpcs
___
enhancement
___
- Updated the RPC URLs for the Taurus network in the `network.ts` file.
- Added multiple WebSocket endpoints to improve connectivity and redundancy.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>network.ts</strong><dd><code>Update Taurus network RPC URLs with new endpoints</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated RPC URLs for the Taurus network.<br> <li> Added multiple new WebSocket endpoints for Taurus.<br>
</details>
</td>
<td><a …
> Change taurus rpcs urls

- packages/auto-drive/src/ipld/builders.ts
- packages/auto-drive/src/ipld/chunker.ts
- packages/auto-drive/src/ipld/nodes.ts
- packages/auto-drive/src/metadata/offchain/file.ts
- packages/auto-drive/src/metadata/offchain/folder.ts
- packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.proto
- packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.ts
enhancement
___
- Introduced `FileUploadOptions` to support encryption and compression during file uploads.
- Updated IPLD builders and chunker functions to accept and process new upload options.
- Enhanced metadata structures to include upload options for both files and folders.
- Extended protobuf schema to define and handle new upload options.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>builders.ts</strong><dd><code>Add file upload options to IPLD builders</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Added upload options (encryption/compression) for head nodes

- .vscode/auto.code-workspace
- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement, configuration changes
___
- Updated all package versions to `1.0.0` to mark a new release.
- Updated dependencies across packages to ensure compatibility with the new version.
- Added a new workspace entry for `Auto-Drive` in the VSCode workspace configuration.
- Updated `gitHead` in several package.json files to reflect the latest commit.
___
<tr>
<td>
<details>
<summary><strong>auto.code-workspace</strong><dd><code>Update workspace configuration with new project</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.vscode/auto.code-workspace
<li>Updated the name of the …
> Publish 1.0.0

- packages/auto-utils/src/constants/network.ts
___
enhancement
___
- Removed the deprecated 'rpc-1' URL from the GEMINI_3H network configuration in the `network.ts` file.
- Ensured that only the active 'rpc-0' URL is listed for the GEMINI_3H network.
___
<tr>
<td>
<details>
<summary><strong>network.ts</strong><dd><code>Remove deprecated RPC URL from GEMINI_3H network configuration</code></dd></summary>
<hr>
<li>Removed deprecated RPC URL 'rpc-1' from the GEMINI_3H network <br>configuration.<br> <li> Updated the <code>rpcUrls</code> array to only include 'rpc-0'.<br>
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/155/files#diff-4fd2d …
> Remove rpc-1 (deprecated) from gemini-3h

- packages/auto-dag-data/src/encryption/index.ts
- packages/auto-dag-data/tests/encryption.spec.ts
The issue was that when a file was encrypted receiving through an stream the exact size of `ENCRYPTING_CHUNK_SIZE` worked well. That's why it went through my tests. I've sorted it out and added a test for controlling this behaviour
___
Bug fix, Tests
___
- Fixed a bug in the decryption logic by correcting buffer handling and subarray indices.
- Added a new test case to verify encryption and decryption functionality with chunking.
- Ensured that the decryption output matches the original file content.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Fix decryption logic and buffer handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Fix encryption bug

- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
As we discussed @webbuf/blake3 requires at least `node20` so as well `@autonomys/auto-dag-data` and `@autonomys/auto-drive` do.
___
enhancement
___
- Added a minimum Node.js version requirement of 20.8.0 to the `package.json` files of `@autonomys/auto-dag-data` and `@autonomys/auto-drive`.
- Ensures compatibility with dependencies that require Node.js version 20 or higher.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Add Node.js version requirement to package.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-dag-data/package.json
- Added a minimum Node.js version …
> Add minimum node version requirement

- packages/auto-consensus/src/utils/format.ts
- packages/auto-consensus/src/utils/index.ts
To facilitate the conversion to PiB or PB
___
enhancement
___
- Added utility functions `formatSpaceToBinary` and `formatSpaceToDecimal` to format space values into human-readable strings using binary and decimal units respectively.
- Updated the `index.ts` to export the newly added format utility functions.
___
<tr>
<td>
<details>
<summary><strong>format.ts</strong><dd><code>Add space formatting utility functions for binary and decimal</code></dd></summary>
<hr>
packages/auto-consensus/src/utils/format.ts
<li>Added utility functions for formatting space in binary and decimal <br>formats.<br> <li> Supports conversion to units like KiB, MiB, GiB, etc., for …
> Adding space formatter utils functions

- packages/auto-utils/src/constants/network.ts
Subscan Autonomys mainnet explorer is up at https://autonomys.subscan.io/
The old subspace URL is not valid anymore
___
enhancement
___
- Updated the Subscan explorer URL in the network constants to point to the new mainnet explorer at `https://autonomys.subscan.io/`.
___
<tr>
<td>
<details>
<summary><strong>network.ts</strong><dd><code>Update Subscan explorer URL for mainnet</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the `SUBSCAN_EXPLORER` URL to the new mainnet explorer.
</details>
</td> …
> Change Subscan URL

- .github/workflows/build.yaml
- README.md
- packages/auto-dag-data/README.md
- packages/auto-drive/README.md
- packages/auto-utils/README.md
Simply trying to unify our different README's from different packages so they all look alike
___
documentation
___
- Unified the formatting of README files across different packages for consistency.
- Added a new package entry for `@autonomys/auto-drive` in the root README.
- Enhanced the `auto-drive` README with badges and additional sections such as License, Additional Resources, and Contact.
- Updated titles in package-specific READMEs to follow a consistent naming convention.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add Auto-Drive package to root README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Unify README's formatting

- packages/auto-dag-data/src/ipld/builders.ts
- packages/auto-dag-data/src/ipld/chunker.ts
- packages/auto-dag-data/src/ipld/nodes.ts
- packages/auto-dag-data/src/metadata/offchain/file.ts
- packages/auto-dag-data/src/metadata/offchain/folder.ts
- packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.proto
- packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.ts
- packages/auto-dag-data/src/utils/metadata.ts
- packages/auto-dag-data/tests/chunker.spec.ts
- packages/auto-dag-data/tests/nodes.spec.ts
IPLD node byte length limit was not strict since extrinsic are limited >> 64kb when a hexadecimal string is sent as data. Since it's intended to publish IPLD nodes in binary format (limited to 65535 bytes) a strict limit is needed. 
The calculated chunk limit (and maxLinksPerNode ) comes from the 64kb limit minus the maximum size of the IPLD metadata.
> update: chunk size limitation

- examples/next/src/hooks/useNetwork.tsx
- packages/auto-utils/src/types/network.ts
Switch network type to use the NetworkId and NetworkName enum in the object type
___
enhancement
___
- Updated the `useNetwork` hook to utilize the `NetworkId` type for better type safety.
- Modified the `Network` type to use `NetworkId` and `NetworkName` enums, enhancing consistency and reducing errors.
- Improved type definitions in the `auto-utils` package for network-related data.
___
<tr>
<td>
<details>
<summary><strong>useNetwork.tsx</strong><dd><code>Update network handling to use `NetworkId` type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
examples/next/src/hooks/useNetwork.tsx
<li>Imported …
> Improve network types

- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement, dependencies
___
- Updated the `@polkadot/extension-dapp` dependency in `packages/auto-utils/package.json` to version `^0.56.2`.
- Updated the `@polkadot/types-codec` devDependency in `packages/auto-xdm/package.json` to version `^14.3.1`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@polkadot/extension-dapp` dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-utils/package.json
<li>Updated the version of <code>@polkadot/extension-dapp</code> dependency from <br><code>^0.54.1</code> to <code>^0.56.2</code>.<br>
</details>
</td>
<td><a …
> Fix packages dedupe conflict

- packages/auto-utils/src/constants/domain.ts
- packages/auto-utils/src/constants/network.ts
- Change Nova for Auto-EVM
- Add future auto-evm domain rpc urls
> Add auto-evm taurus and change domain name

- packages/auto-drive/package.json
- packages/auto-drive/src/api/calls/read.ts
- packages/auto-drive/src/api/models/common.ts
- packages/auto-drive/src/utils/observable.ts
- yarn.lock
Creating the examples for interacting with auto-drive backend I came out with some issues:
- 1. Wrongly typed paginated responses: It didn't consider pagination
- 2. RXJS is a commonjs package that in a ESM enviroment should be imported in this way:
```ts
import rxjs from 'rxjs'
```
rather than:
```ts
import {xyz} from 'rxjs'
```
> Fix few issues in auto-drive pkg

- packages/auto-drive/src/api/connection.ts
As described in the nginx config in this [PR](https://github.com/autonomys/auto-drive/pull/113), default URL has changed to have the postfix /api
> Update API url

- packages/auto-dag-data/src/encryption/index.ts
- packages/auto-drive/src/utils/observable.ts
- yarn.lock
Adding examples to auto-drive backend I figured out that there were some issues using the package in web clients. These fixes are to solved them. These changes work also in nodejs server. 
For making this version work on the web client some webpack config is needed to be setup. I'll add an issue for solving this internally so no webpack is needed.
> Fix environmental issues

- packages/auto-drive/src/api/calls/index.ts
- packages/auto-drive/src/api/wrappers.ts
- packages/auto-drive/src/fs/wrappers.ts
Added a namespace to the internal api calls to avoid confusion between the main functions (e.g `downloadFile`) and the internal functions (e.g `downloadObject`)
> Add namespace to api calls

- examples/auto-drive-create-next-app/export.mjs
- packages/auto-drive/README.md
- packages/auto-drive/src/api/connection.ts
- packages/auto-drive/src/api/networks.ts
This PR adds support for multi-chain connection. Pending the deployment of main-net to merge it
> Multi chain connector

- packages/auto-drive/package.json
- yarn.lock
Pkg `@autonomys/auto-utils` is used in `@autonomys/auto-drive` pkg but wasn't a dependency
> Fix missing dependency

- packages/auto-consensus/src/utils/format.ts
This is to allow us to use the number separately from the label (and so for example adding animation to the number if between two query it increase)
> Add formatSpaceToBinaryAsObject and formatSpaceToDecimalAsObject

- packages/auto-drive/README.md
After this update https://github.com/autonomys/auto-drive/pull/193, this doc got outdated.
> Update doc on how to create an Api Key

- packages/auto-consensus/src/types/staking.ts
- packages/auto-consensus/src/utils/parse.ts
`withdrawalInShares` inside parseWithdrawal become null ounce the withdrawal is unlocked from what I see, this was creating an issue with the parsing function.
> Fix parseWithdrawal to support null withdrawalInShares

- packages/auto-consensus/src/info.ts
- packages/auto-consensus/src/types/block.ts
- packages/auto-consensus/src/types/extrinsic.ts
- packages/auto-consensus/src/types/index.ts
- packages/auto-consensus/src/utils/parse.ts
- Improve flexibility of block-related query to accept block hash arguments
- Add parsing function to parse block extrinsic
- Add filter function to filter only specific transfer extrinsic
> Improve auto consensus query fn

- lerna.json
- package.json
- packages/asynchronous/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
The standalone publication of the @autonomys/asynchronous v.1.4.0 was missing the compiled package.
> Published v1.4.1

- packages/auto-xdm/src/index.ts
- packages/auto-xdm/src/info.ts
- packages/auto-xdm/src/messenger.ts
This pull request includes several changes to the `packages/auto-xdm` module, focusing on exporting new functionalities and adding new methods to handle messenger channels. The most important changes are grouped by theme and listed below:
* [`packages/auto-xdm/src/index.ts`](diffhunk://#diff-1890068248bde88db321056bacc97c7550d1d24e19dc50075ccbd469114ae865R2): Added export for `messenger` module.
* [`packages/auto-xdm/src/info.ts`](diffhunk://#diff-58ef5808f0a1f992156be7f77b8904ae2ecf286d7cec50814d4bd99cd7cde9efL4-R16): Added new methods `channels`, `consensusChannels`, and `domainChannels` to query messenger channels using `ApiPromise` and `Codec`.
* [`packages/auto-xdm/src/messenger.ts`](diffhunk://#diff-32fcd7a371353fa37e93f3dd03bcc7756fc8f5d0ea7c37aca75e90e231f73787R1-R11): Introduced …
> Feat: Add more XDM function

- packages/auto-utils/src/address.ts
- packages/auto-utils/src/constants/wallet.ts
it should be `6094` to produce su address, not `2254` (st addresses)
> Fix: Default ss58 prefix

- packages/rpc/src/models/common.ts
- packages/rpc/src/rpc/client.ts
- packages/rpc/src/rpc/server.ts
- packages/rpc/src/rpc/types.ts
The controller for rpc responses expected a `string` where it should receive a `MessageResponseQuery`
Also I updated the type `MessageResponseQuery` for easing the devEx
> Fix rpc response

- packages/rpc/__test__/rpc/index.spec.ts
- packages/rpc/src/models/server.ts
- packages/rpc/src/rpc/server.ts
- packages/rpc/src/rpc/types.ts
- packages/rpc/src/ws/server.ts
- RPC Callbacks were passing the whole message rather than the expect `params` field
- The server listening was a bit more tricky than expected so I added a new method in rpc for listening
> Fixing/enhancing RPC server

- lerna.json
- packages/asynchronous/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/file-caching/package.json
- packages/rpc/__test__/rpc/typed.spec.ts
- packages/rpc/package.json
- packages/rpc/src/rpc/api/definition.ts
- packages/rpc/src/rpc/api/typing.ts
- packages/rpc/src/rpc/server.ts
- packages/rpc/src/rpc/types.ts
- yarn.lock
In addition to the Message (client request + server response) rpc feature server should be able to send messages to the client for enabling mechanism like subscription to events.
This wasn't support before and this PR enables server to send notifications
> Add notifications support to Type-Safe RPC

- packages/utility/file-caching/src/fileCache.ts
Using nonBlocking policy was making that no file was stored in sqlite cache leading to cache loss when service reboots. 
Additionally, I was generating incorrectly the path for the file to be stored though it wasn't causing problems due to the partiotioning of folders.
> fix: caching policy

- packages/utility/file-caching/src/utils.ts
Cache is failing in some cases when a folder already exists but it's executed a `mkdir`
> fix: failing mkdir when dir exists

- packages/auto-mcp-servers/README.md
- packages/auto-mcp-servers/package.json
- packages/auto-mcp-servers/src/bin/main.ts
- yarn.lock
This PR fixes the `@autonomys/auto-mcp-servers` package by implementing a multi-server architecture with a unified entry point, allowing users to direct to the desired underlying mcp-server.
- **Multi-server architecture**: Added a main entry point (`bin/main.ts`) that can dispatch to different MCP servers
- **Improved binaries**: Updated package.json with multiple bin entries for both direct server execution and the main dispatcher
- **Build process**: Added prepublishOnly script to ensure binaries are properly executable after build
- **Documentation**: Updated README with simplified installation instructions using npx
- Users can now run servers either directly (`auto-drive-server`) or through the main entry point (`auto-mcp-servers auto-drive`)
- Better Claude Desktop and other …
> Fix auto-mcp-server package usage

- packages/auto-mcp-servers/README.md
- packages/auto-mcp-servers/package.json
- packages/auto-mcp-servers/src/auto-drive/handlers.ts
- packages/auto-mcp-servers/src/auto-drive/index.ts
This pull request introduces significant updates to the `auto-mcp-servers` package, including the addition of new handlers for Auto Drive functionality, improved modularization, and minor version updates. The changes enhance the package's capability to interact with the Autonomys Network for uploading, downloading, and searching objects, while also improving maintainability.
* Added `createAutoDriveHandlers` in `handlers.ts`, which provides modularized handlers for uploading, downloading, and searching objects on the Autonomys Network. This includes robust error handling and support for text-based file downloads. (`packages/auto-mcp-servers/src/auto-drive/handlers.ts`)
* Updated `autoDriveServer` to include new tools for downloading and searching objects (`download-object` and …
> Feature: Add download object and search object tools to auto-drive mcp

- packages/auto-agents/jest.config.js
- packages/auto-agents/package.json
- packages/auto-agents/src/experiences/cidManager.ts
- packages/auto-agents/src/experiences/experienceManager.ts
- packages/auto-agents/src/experiences/experienceStorage.ts
- packages/auto-agents/src/experiences/index.ts
- packages/auto-agents/src/experiences/storage.ts
- packages/auto-agents/src/index.ts
- packages/auto-agents/tsconfig.json
This pull request updates the `packages/auto-agents` package to fully adopt ES module syntax. The changes include setting the package type to "module," updating import paths to include `.js` extensions, and adjusting TypeScript configurations for proper module resolution.
This was discovered to be required when trying to update `autonomys-agents` to use `auto-agents`, due to `auto-dag-data` dependency.
* [`packages/auto-agents/package.json`](diffhunk://#diff-70218131c9706430866405f0b5efa8b22ddcab14e39ad9c6144d40b49402205eR6): Added `"type": "module"` to specify the package as an ES module.
* Updated import statements across multiple files to include `.js` extensions for compatibility with ES module syntax:
- `packages/auto-agents/src/experiences/cidManager.ts`
- …
> Convert auto-agents to nodenext

- packages/utility/rpc/__test__/rpc/typed.spec.ts
- packages/utility/rpc/__test__/ws/server.spec.ts
- packages/utility/rpc/src/rpc/api/definition.ts
- packages/utility/rpc/src/rpc/client.ts
- packages/utility/rpc/src/rpc/server.ts
- packages/utility/rpc/src/rpc/types.ts
- packages/utility/rpc/src/utils/http.ts
- packages/utility/rpc/src/utils/misc.ts
- packages/utility/rpc/src/utils/websocket.ts
- packages/utility/rpc/src/ws/server.ts
- packages/utility/rpc/src/ws/types.ts
- packages/utility/rpc/tsconfig.json
The server was only responding to messages when connected only through `ws`. This means if a http request was performed the server won't respond this PR updates this behaviour
> feat: make server respond to http post request

- .gitignore
- packages/auto-agents/src/experiences/cidManager.ts
- packages/auto-agents/src/experiences/types.ts
- packages/auto-mcp-servers/README.md
- packages/auto-mcp-servers/package.json
- packages/auto-mcp-servers/src/auto-drive/handlers.ts
- packages/auto-mcp-servers/src/auto-drive/index.ts
- packages/auto-mcp-servers/src/auto-experiences/handlers.ts
- packages/auto-mcp-servers/src/auto-experiences/index.ts
- packages/auto-mcp-servers/src/bin/auto-drive.ts
- packages/auto-mcp-servers/src/bin/auto-experiences.ts
- packages/auto-mcp-servers/src/bin/main.ts
- packages/auto-mcp-servers/src/index.ts
- yarn.lock
This PR adds a new MCP server for managing agent experiences, along with several improvements to the existing codebase.
1. Added new Auto Experiences server with two main tools:
- `save-experience`: Saves agent experience data to AutoDrive and updates the last experience CID
- `retrieve-experience`: Retrieves agent experiences using their CID
2. Enhanced CID Manager functionality:
- Made contract info optional with graceful fallback to local-only storage
- Improved error handling and offline mode support
- Refactored provider initialization logic
3. Infrastructure improvements:
- Added new binary `auto-experiences-server` for standalone operation
- Updated main server to support both Auto Drive and Auto Experiences
- Enhanced error handling and logging across the codebase
4. Type safety …
> Add Agent Experiences MCP Server and Improve CID Manager functionality

- packages/utility/rpc/src/ws/server.ts
Previously, when the `ws` server was built on top of an express server all the routes declared in express were effectively wiped. 
Now the `onHttpRequest` callback only is executed over the route `/ws` allowing to wrap all the `'request'` callbacks ignoring the default handler in express that returns `Not Found (404)`
> fix: express http requests handling

- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-design-system/package.json
- packages/auto-drive/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/design-tokens/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/__test__/rpc/typed.spec.ts
- packages/utility/rpc/package.json
- packages/utility/rpc/src/rpc/api/definition.ts
- packages/utility/rpc/src/ws/server.ts
- packages/utility/user-session/package.json
- yarn.lock
The handler for RPC http request should've ensured that is `method=POST` and `route=/ws`
> Fix missing wrap of RPC handler http request

- packages/utility/asynchronous/package.json
- packages/utility/asynchronous/src/streams/index.ts
- yarn.lock
Add a method for duplicating readable streams with protection against backpressuring
> feat: add `forkStream` method to `@autonomys/asynchronous`

- packages/auto-drive/src/api/calls/download.ts
- packages/auto-drive/src/api/calls/read.ts
- packages/auto-drive/src/api/calls/upload.ts
- packages/auto-drive/src/api/calls/write.ts
- packages/auto-drive/src/api/handler.ts
- packages/auto-drive/src/api/networks.ts
- packages/auto-drive/src/api/types.ts
- packages/auto-drive/src/api/wrappers.ts
Similarly to https://github.com/autonomys/auto-drive/pull/366 redirect all downloads through public instances making the cache hit much more times.
> feat: redirect to public instances for downloads

- packages/auto-mcp-servers/src/bin/main.ts
The `auto-drive` MCP server was failing to start due to an unwanted dependency on environment variables from `auto-experiences` (`AGENT_PATH`, `AGENT_NAME`, etc.). This occurred because the main entry point was statically importing both servers, causing all modules to be loaded and executed regardless of which server was requested.
- Changed static imports to dynamic imports in `src/bin/main.ts`
- Each server module is now only loaded when specifically requested
- `packages/auto-mcp-servers/src/bin/main.ts`: Replace static imports with dynamic imports
- `auto-drive-server` now starts without requiring `AGENT_PATH` environment variable
- `auto-experiences-server` continues to work as expected with its required environment variables
> fix(auto-mcp-servers): remove cross-dependency on env vars

- packages/utility/file-caching/src/fileCache.ts
Problem: 
`Cache.has` method was not returning a boolean but throwing if failing
Solution: 
Make `Cache.has` method return boolean by wrapping promise in then/catch structure
> fix: `Cache.has` method was not returning a boolean but throwing if failing

- packages/utility/rpc/src/rpc/api/definition.ts
**Problem:**
When two notifications are declared in the same rpc definitions the type received as content of notifications is the merge of the two defined notifications content type.
**Solution:**
Avoid types to merge
> feat: improve type infer

- packages/utility/rpc/src/rpc/api/definition.ts
- packages/utility/rpc/src/rpc/api/typing.ts
Sometimes RPC servers might require to pass additional headers (e.g `Authorization` header for auth) for covering this PR separates the ApiClient type into WsClient w/o `httpOpts` and HttpClient that accepts both HttpOptions for the whole client and for each method, having a bigger priority the method options that the client options.
> feat: enable passing http options to HttpClient & methods

- packages/auto-consensus/src/domain.ts
- scripts/staking-position-calculator.ts
This pull request introduces a new utility function, `headDomainNumber`, to retrieve the latest block number for a specific domain. Additionally, it cleans up the handling of withdrawal data in staking-position calculator.
* [`packages/auto-consensus/src/domain.ts`](diffhunk://#diff-324a183e547d8f0abae0694022cec343511083ffe1f4733cf5ec2a294f0c6e46R161-R205): Added the `headDomainNumber` function, which queries the latest block number for a specific domain and handles cases where no blocks are found. Includes comprehensive documentation and an example usage.
> feat: add headDomainNumber function to retrieve latest block number for a specific domain

- CHANGELOG.md
- examples/auto-drive-create-next-app/package.json
- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-design-system/package.json
- packages/auto-drive/package.json
- packages/auto-files/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/design-tokens/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
This pull request primarily updates the version across multiple files and packages from `1.5.7` to `1.5.9` and makes corresponding dependency updates. Additionally, it introduces new features and bug fixes documented in the changelog.
* Added new features, including simplifying `nominatorPosition` to use runtime API and input sanitization for `FilePreview`.
* Fixed runtime upgrade compatibility for operator epoch share prices.
* Bumped version to `1.5.9`.
* Updated the version from `1.5.7` to `1.5.9` in `lerna.json`, multiple `package.json` files, and `package-lock.json`. [[1]](diffhunk://#diff-1796d8effff5f3271dfcf4c44ba3b8a7a5d5d4b213afe27eee2f72dddcc4fe50L3-R3) [[2]](diffhunk://#diff-d7decfac1c821bf150a00819017759e1d3d457c43411a2abb2ab50b3dbd35180L3-R9) …
> chore: release v1.5.9

- packages/auto-utils/src/constants/network.ts
- packages/auto-utils/src/network.ts
- packages/auto-utils/src/types/network.ts
This pull request updates the network configuration in the `auto-utils` package to introduce the Chronos testnet and deprecate the Taurus testnet. The changes reorganize network definitions, add new RPC and explorer URLs for Chronos, and introduce a deprecation warning for Taurus to guide users toward Chronos or Mainnet.
**Network Configuration Updates:**
* Added Chronos testnet to `NetworkId` and `NetworkName` enums, and defined its RPC and explorer URLs in `network.ts`. [[1]](diffhunk://#diff-4fd2dc1471be3439397f28b938666936f488d249dfbac7440079c77f301f041bR9-R17) [[2]](diffhunk://#diff-4fd2dc1471be3439397f28b938666936f488d249dfbac7440079c77f301f041bR30) [[3]](diffhunk://#diff-4fd2dc1471be3439397f28b938666936f488d249dfbac7440079c77f301f041bL60-R96)
* Updated the `networks` array: Chronos …
> feat: add chronos testnet to networks

- CHANGELOG.md
- examples/auto-drive-create-next-app/package.json
- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-design-system/package.json
- packages/auto-drive/package.json
- packages/auto-files/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/design-tokens/package.json
- packages/utility/file-server/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
New version released, feature and refactoring highlights:
* Enhanced the `totalIssuance` function to support domain queries.
* Refactored network explorer details to remove Astral and cleaned up RPCs.
> chore: v1.5.16

- packages/auto-utils/__test__/units.test.ts
- packages/auto-utils/src/number.ts
- packages/auto-utils/tsconfig.json
This pull request adds robust utilities for precise token amount conversions and formatting, particularly for AI3 tokens and their smallest unit (Shannon). It introduces new functions for lossless conversion between decimal strings and bigint representations, improves documentation for existing functions, and provides comprehensive unit tests to ensure correctness. Additionally, TypeScript configuration is updated for modern language features.
Closes #474 
**New token conversion utilities:**
* Added `parseUnits` and `formatUnits` for generic, lossless conversion between human-readable decimal strings and smallest unit bigints, supporting custom decimals and rounding/truncation options.
* Added `ai3ToShannons` and `shannonsToAi3` for precise conversion between AI3 decimal strings and …
> feat: add precise token precision conversion functions

- packages/auto-consensus/src/index.ts
- packages/auto-consensus/src/transactionFees.ts
Adds support for calling the state query `transactionFees.transactionByteFee`
> feat: add transactionByteFee function and schema
