- .eslintignore
- .eslintrc
- .gitignore
- .prettierrc
- .vscode/auto.code-workspace
- .vscode/extensions.json
- .vscode/settings.json
- package.json
- yarn.lock
Simply adding prettier, eslint and .vscode/
> Setup-monorepo-workspace

- packages/auto-consensus/README.md
- packages/auto-consensus/package.json
- packages/auto-id/README.md
- packages/auto-id/package.json
- packages/auto-utils/README.md
- packages/auto-utils/package.json
Simple PR to set each of the packages so they publish only the dist/ directory and readme.md
> Define in each packages.json what gets exported to the package

- .github/workflows/build.yaml
- only run on pr and push to main, ignore .md files
> restrict workflow run on

- scripts/run-operator.sh
> Fix domain port

- examples/node/.env.local
- examples/node/README.md
- examples/node/package.json
- examples/node/src/deregister-operator.ts
- examples/node/src/nominate-operator.ts
- examples/node/src/operator.ts
- examples/node/src/operators.ts
- examples/node/src/register-operator.ts
- examples/node/src/unlock-funds.ts
- examples/node/src/unlock-nominator.ts
- examples/node/src/utils/index.ts
- examples/node/src/utils/setup.ts
- examples/node/src/utils/signAndSend.ts
- examples/node/src/withdraw-stake.ts
- packages/auto-consensus/src/index.ts
in /examples/node examples of how to use auto-consensus for staking
running `yarn all` will run all extrinsics one after the other
> Create reusable example scripts to cover all staking functions

- packages/auto-consensus/src/batch.ts
- packages/auto-consensus/src/index.ts
- packages/auto-consensus/src/remark.ts
> Add batch and remark

- examples/next/src/components/dropdown/AutoConsensus.tsx
- examples/next/src/components/dropdown/AutoId.tsx
- examples/next/src/components/dropdown/Network.tsx
- examples/next/src/components/layout/Header.tsx
- examples/next/src/hooks/useApi.tsx
- examples/next/src/hooks/useNetwork.tsx
This allow the next JS example to run against gemini 3h or localhost
> Improve next example to run on Gemini 3h

- packages/auto-consensus/__test__/balances.test.ts
- packages/auto-consensus/__test__/helpers/setup.ts
- packages/auto-consensus/__test__/helpers/tx.ts
- packages/auto-consensus/__test__/staking.test.ts
- packages/auto-consensus/__test__/transfer.test.ts
- packages/auto-utils/__test__/wallet.test.ts
- packages/auto-utils/src/utils/sign.ts
- Fix auto-consensus tests following some recent change
- Improve wallet tests in auto-utils
- Fix wrong async label on publickey function
> Fix auto-consensus tests

- .vscode/auto.code-workspace
- packages/auto-xdm/README.md
- packages/auto-xdm/jest.config.js
- packages/auto-xdm/package.json
- packages/auto-xdm/src/transfer.ts
- packages/auto-xdm/tsconfig.json
- yarn.lock
> Create the auto xdm basic package

- .github/workflows/pr-ai-agent.yaml
adding AI Pull request reviewer CI workflow
> add PR AI agent CI workflow

- packages/auto-consensus/src/domain.ts
- packages/auto-consensus/src/index.ts
- packages/auto-consensus/src/staking.ts
- packages/auto-consensus/src/types/domain.ts
- packages/auto-consensus/src/types/index.ts
- packages/auto-consensus/src/types/staking.ts
- packages/auto-consensus/src/utils/index.ts
- packages/auto-consensus/src/utils/parse.ts
- domainRegistry
- domainStakingSummary
- latestConfirmedDomainBlock
- deposits
- withdrawals
___
Enhancement, Documentation
___
- Added functions to query domain registry, domain staking summary, and latest confirmed domain block.
- Implemented error handling for the new functions.
- Added functions to query deposits and withdrawals.
- Refactored imports and types in staking module.
- Added and exported types for domain and staking-related data structures.
- Added and exported parsing utilities for domain and staking data.
___
<tr>
<td>
<details>
<summary><strong>domain.ts</strong><dd><code>Add domain-related read functions with error …
> Add more domains and staking related read functions

- packages/auto-consensus/src/balances.ts
- packages/auto-consensus/src/domain.ts
- packages/auto-consensus/src/info.ts
- packages/auto-consensus/src/staking.ts
- packages/auto-utils/src/types/wallet.ts
___
Enhancement
___
- Changed the type of `api` parameter from `ApiPromise` to `Api` in multiple modules (`balances.ts`, `domain.ts`, `staking.ts`)
- Updated import statements to reflect the new type `Api`
- Added a new type `ApiAtBlockHash` and updated the `Api` type to include it
- Removed an unused import statement in `info.ts`
___
<tr>
<td>
<details>
<summary><strong>balances.ts</strong><dd><code>Update `api` parameter type in balances module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-consensus/src/balances.ts
<li>Changed type of <code>api</code> parameter from …
> Improve typing to support api.at

- README.md
- examples/next/package.json
- examples/next/src/components/layout/Footer.tsx
- examples/node/package.json
- package.json
- packages/auto-consensus/package.json
- packages/auto-id/package.json
- packages/auto-id/tests/utils.test.ts
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- scripts/download.sh
> replace github subspace by autonomys

- packages/auto-consensus/src/types/staking.ts
- packages/auto-consensus/src/utils/parse.ts
Apply same parsing as we did in Astral, so then these functions can be used directly in astral
___
Enhancement, Bug fix
___
- Added new types `RawWithdrawal` and `WithdrawalUnlock` to better structure withdrawal data.
- Modified existing types `RawDeposit` and `Deposit` to handle nullable pending deposits and changed `operatorId` type from `bigint` to `number`.
- Updated `Withdrawal` type to use `WithdrawalUnlock` and changed `totalWithdrawalAmount` to `bigint`.
- Enhanced `parseDeposit` function to handle nullable pending deposits.
- Improved `parseWithdrawal` function to convert string amounts to `bigint` and added mapping for `withdrawals`.
___
<tr> …
> Improve deposit and withdrawals parsing

- examples/next/src/hooks/useNetwork.tsx
- examples/node/src/utils/setup.ts
- lerna.json
- packages/auto-consensus/__test__/helpers/setup.ts
- packages/auto-consensus/package.json
- packages/auto-id/package.json
- packages/auto-utils/__test__/network.test.ts
- packages/auto-utils/__test__/wallet.test.ts
- packages/auto-utils/package.json
- packages/auto-utils/src/constants/network.ts
- packages/auto-xdm/package.json
- yarn.lock
- removed `autonomys-` prefix on each network name
- Change some of the links for autonomys.xyz
This is a braking change so I'm planning to publish this as 0.2.0 when approved
___
Enhancement, Bug fix
___
- Removed `autonomys-` prefix from network IDs across various files.
- Updated network names and RPC URLs to use HTTPS.
- Changed explorer URL to `autonomys.xyz`.
- Fixed a typo in network ID within network tests.
___
<tr>
<td>
<details>
<summary><strong>useNetwork.tsx</strong><dd><code>Simplify network ID for localhost in useNetwork hook</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
examples/next/src/hooks/useNetwork.tsx
- Removed …
> Simplify network name and fix urls

- packages/auto-utils/src/constants/network.ts
- packages/auto-utils/src/constants/token.ts
- packages/auto-utils/src/types/index.ts
- packages/auto-utils/src/types/network.ts
- packages/auto-utils/src/types/token.ts
___
enhancement
___
- Added `DEFAULT_TOKEN_SYMBOL` constant with value 'ATC'
- Added `DEFAULT_TOKEN_NAME` constant with value 'Auto Token'
___
<tr>
<td>
<details>
<summary><strong>token.ts</strong><dd><code>Add default token symbol and name constants</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-utils/src/constants/token.ts
<li>Added <code>DEFAULT_TOKEN_SYMBOL</code> constant with value 'ATC'<br> <li> Added <code>DEFAULT_TOKEN_NAME</code> constant with value 'Auto Token'<br>
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/93/files#diff-2184 …
> Add default token details

- packages/auto-utils/src/constants/domain.ts
- packages/auto-utils/src/constants/index.ts
- packages/auto-utils/src/constants/network.ts
- packages/auto-utils/src/network.ts
- packages/auto-utils/src/types/domain.ts
- packages/auto-utils/src/types/network.ts
___
Enhancement
___
- Created a new `domain.ts` file to define domain constants, including the `DomainId` enum and `domains` object.
- Updated `index.ts` to export the new domain constants.
- Refactored `network.ts` to remove the `DomainId` enum and domain definitions, and instead import and use the new domain constants.
___
<tr>
<td>
<details>
<summary><strong>domain.ts</strong><dd><code>Define domain constants in a new file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-utils/src/constants/domain.ts
<li>Created a new file …
> Split domains from network

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement, dependencies
___
- Updated the version from 0.2.0 to 0.3.0 in `lerna.json`.
- Updated the package version from 0.2.0 to 0.3.0 in `packages/auto-consensus/package.json`, `packages/auto-id/package.json`, `packages/auto-utils/package.json`, and `packages/auto-xdm/package.json`.
- Updated the dependency `@autonomys/auto-utils` version to 0.3.0 in `packages/auto-consensus/package.json`, `packages/auto-id/package.json`, and `packages/auto-xdm/package.json`.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Bump version in lerna configuration file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Pumped version to 0.3.0

- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Updated version numbers across multiple packages and configuration files to 0.5.0.
- Updated dependencies to use the new version ^0.5.0 where applicable.
- Updated `gitHead` hashes in several package.json files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Update package-lock.json version to 0.5.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
examples/next/package-lock.json
- Updated version from 0.1.0 to 0.5.0.
</details>
</td>
<td><a …
> Bumped to 0.5.0

- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Updated version numbers from 0.5.0 to 0.5.1 across multiple package.json and package-lock.json files.
- Updated dependencies to use `@autonomys/auto-utils` version 0.5.1 in relevant packages.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Update version in package-lock.json for Next example</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
examples/next/package-lock.json
- Updated version from 0.5.0 to 0.5.1.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/108/files#diff-d7decfac1c821bf150a00819017759e1d3d457c43411a2abb2ab50b3dbd35180">+2 …
> Version 0.5.2

- .vscode/auto.code-workspace
- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
(I had some NPM permissions issues that prevented me to publish 0.6.0 to npm, so 0.6.1 is published on npm instead :) )
___
enhancement, configuration changes
___
- Updated the version numbers across multiple packages and examples from 0.5.3 to 0.6.0 or 0.6.1.
- Added MIT license field to several package.json files.
- Added `Auto-Drive` to the VSCode workspace configuration.
- Updated dependencies to reflect the new version 0.6.1 for `@autonomys/auto-utils`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td>
<details>
<summary><strong>auto.code-workspace</strong><dd><code>Add Auto-Drive to VSCode workspace configuration</code>&nbsp; &nbsp; &nbsp; …
> Publish 0.6.1

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
This pull request includes version updates across multiple packages to ensure consistency and compatibility. The most important changes involve updating the version numbers and dependencies in various `package.json` files.
Version updates:
* [`lerna.json`](diffhunk://#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821L3-R3): Updated the version from `0.6.2` to `0.6.3`.
* [`packages/auto-consensus/package.json`](diffhunk://#diff-1317227b031692c486b9ee7654f894e5545a6a004c0bf89192b9a89d10db9acfL3-R3): Updated the version from `0.6.2` to `0.6.3` and the `@autonomys/auto-utils` dependency version. [[1]](diffhunk://#diff-1317227b031692c486b9ee7654f894e5545a6a004c0bf89192b9a89d10db9acfL3-R3) [[2]](diffhunk://#diff-1317227b031692c486b9ee7654f894e5545a6a004c0bf89192b9a89d10db9acf …
> Publish 0.6.3

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Updated the version across multiple packages from 0.6.3 to 0.6.5.
- Updated the `@autonomys/auto-utils` dependency version in several packages.
- Updated the `gitHead` to reflect new commit hashes in all package.json files.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update version in lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.6.3 to 0.6.5.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/118/files#diff …
> Version 0.6.5

- packages/auto-utils/src/index.ts
- packages/auto-utils/src/string.ts
- Stringify objects that include bigint
- Shorten address, public key, and other string
- Capitalize first letter
- Fix the length of a entry (useful for block, event, log and extrinsic to make the order by id work even if the entry are returned as string)
___
enhancement
___
- Introduced new string utility functions in `string.ts` for various string manipulations.
- Added `stringify` function to convert objects with bigint to JSON.
- Added `shortString` function to shorten strings like addresses or keys.
- Added `capitalizeFirstLetter` function to capitalize the first letter of a string.
- Added `fixLengthEntryId` function to format entry IDs with fixed length.
- Updated `index.ts` to export the new string utility functions.
___
<table><thead><tr><th></th><th align="left">Relevant …
> Add some basic string utility functions

- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
This latest version includes:
- #119 
- #120 
- #121
> Publish 0.6.6

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of multiple packages from 0.6.6 to 0.6.7.
- Updated the `@autonomys/auto-utils` dependency version in several packages.
- Updated `gitHead` to reflect the new commit hash across all packages.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in Lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.6.6 to 0.6.7.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/126/files#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b …
> Publish 0.6.7

- packages/auto-utils/package.json
- yarn.lock
Update polkadot dependencies in auto-utils to 13.1.1 and run yarn dedupe
___
enhancement, dependencies
___
- Updated `@polkadot/api` dependency to version 13.1.1.
- Updated `@polkadot/extension-dapp` dependency to version 0.54.1.
- Updated `@polkadot/types-codec` devDependency to version 13.1.1.
- Ran `yarn dedupe` to clean up duplicate dependencies.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update Polkadot dependencies to newer versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-utils/package.json
<li>Updated <code>@polkadot/api</code> dependency …
> Update polkadot dependencies and run dedupe

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
This includes mainly the fix to blockchainSize() in auto-consensus and some minor improvements
___
enhancement
___
- Updated the version across multiple packages from 0.6.7 to 0.6.8.
- Updated the dependency `@autonomys/auto-utils` to version 0.6.8 in several packages.
- This release includes fixes and improvements, particularly in the `auto-consensus` package.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.6.7 to 0.6.8.
</details> …
> Publish 0.6.8

- packages/auto-utils/src/constants/network.ts
- packages/auto-utils/src/constants/token.ts
- Add support for Taurus tesnet
- Change token symbol from ATC to AI3
___
enhancement
___
- Added support for the Taurus testnet by introducing a new network configuration in the `network.ts` file, including RPC URLs and explorers.
- Updated the `NetworkId` enum to include `TAURUS`.
- Changed the default token symbol from `ATC` to `AI3` in the `token.ts` file.
___
<tr>
<td>
<details>
<summary><strong>network.ts</strong><dd><code>Add Taurus testnet configuration and network ID</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added <code>TAURUS</code> to the …
> Add support for Taurus testnet

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of the project and all related packages from `0.6.8` to `0.7.0`.
- Updated the dependency `@autonomys/auto-utils` to version `^0.7.0` in relevant packages.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in Lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated project version from `0.6.8` to `0.7.0`.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/134/files#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821">+1/-1</a>&nbs …
> Publish v0.7.0

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated version numbers from 0.7.2 to 0.7.3 across multiple packages.
- Updated `@autonomys/auto-utils` dependency to version ^0.7.3 in relevant packages.
- Updated `gitHead` references in package.json files.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update Lerna configuration version to 0.7.3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.7.2 to 0.7.3.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/142/files#diff-2d72bd …
> Publish 0.7.3

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Updated the version across multiple packages from `0.7.3` to `0.7.4`.
- Updated the dependency `@autonomys/auto-utils` to version `^0.7.4` in several packages.
- Updated the `lerna.json` configuration to reflect the new version.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in Lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from `0.7.3` to `0.7.4`.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/143/files#diff-2d72bdead8afa0798d18995311992d684348a6 …
> Version 0.7.4

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
Bumped to 0.8.2 because I published wrongly the packages in 0.8.1
___
enhancement
___
- Updated the version across multiple packages from 0.7.4 to 0.8.2.
- Updated dependencies to align with the new version 0.8.2.
- Added `gitHead` field in `auto-drive` package for version tracking.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update version in lerna configuration file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 0.7.4 to 0.8.2.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/147/files#di …
> Version 0.8.2

- packages/auto-utils/src/constants/network.ts
___
enhancement
___
- Updated the MAINNET network configuration to include additional RPC URLs.
- Added new RPC endpoints for `autonomys.xyz` to enhance network connectivity.
___
<tr>
<td>
<details>
<summary><strong>network.ts</strong><dd><code>Update MAINNET RPC URLs with new endpoints</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated the <code>rpcUrls</code> array for the MAINNET network.<br> <li> Added new RPC URLs for <code>autonomys.xyz</code>.<br> <li> Expanded the list to include multiple RPC endpoints.<br> …
> Change rpc for autonomys labs rpcs

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of the project and all packages from 1.0.0 to 1.0.1.
- Updated dependencies to ensure compatibility with the new version.
- Updated `gitHead` in all package.json files to reflect the latest commit hash.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update project version in Lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 1.0.0 to 1.0.1.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/151/files#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2 …
> Publish 1.0.1

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of all packages from `1.0.1` to `1.0.2`.
- Updated dependencies to ensure compatibility with the new version.
- Adjusted `lerna.json` to reflect the new version.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update version in lerna configuration file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from `1.0.1` to `1.0.2`.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/156/files#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e482 …
> Publish 1.0.2

- packages/auto-dag-data/src/ipld/utils.ts
- packages/auto-drive/src/api/calls/upload.ts
- packages/auto-drive/src/api/models/uploads.ts
- packages/auto-drive/src/api/wrappers.ts
Implements the changes in https://github.com/autonomys/auto-drive/pull/85 into the SDK returning the head CID when an upload is completed successfully
___
enhancement, bug fix
___
- Enhanced the upload functionality to return the CID upon completion for both files and folders.
- Updated TypeScript imports and exports to use `.js` extensions instead of `.ts`.
- Defined a new type `CompleteUploadResponse` to ensure the response from `completeUpload` is correctly typed.
- Adjusted TypeScript configuration by removing unnecessary options.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>4 files</summary><table>
<tr>
<td>
<details>
<summary><strong>utils.ts</strong><dd><code>Add and export CID …
> Upload folder & upload file returns head CID

- packages/auto-drive/src/api/connection.ts
Allow to use oauth authentication in api connection. This is necessary for auto-drive application
___
Enhancement
___
- Added OAuth authentication support in the API connection, allowing the use of Google and Discord as providers.
- Updated the `completeUpload` function to return a typed response (`CompleteUploadResponse`).
- Modified upload functions to return `CID`, enhancing the upload process with more detailed responses.
- Introduced `OAuthProvider` enum and `AuthProvider` type to manage authentication methods.
___
<tr>
<td>
<details>
<summary><strong>utils.ts</strong><dd><code>Add CID import and export in utils</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> Enable oauth authentication in api connection

- lerna.json
- package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
As you can see I bumped twice (from 1.0.2->1.0.4) that's because I missed to build one of the packages leading to wrong package published at (1.0.3). For avoiding this I've added a prepublishing script that runs the build on all packages.
___
enhancement
___
- Bumped version numbers from 1.0.2 to 1.0.4 across multiple packages to ensure consistency.
- Added a `prepublish` script in the root `package.json` to automatically build packages before publishing.
- Updated dependencies to match the new version 1.0.4 in several packages.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Bump version to 1.0.4 in lerna.json</code>&nbsp; …
> v1.0.4 + Prepublishing script

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
enhancement
___
- Updated the version of multiple packages from 1.0.4 to 1.0.5.
- Updated dependencies to ensure compatibility with the new version.
- This version bump is reflected across several packages including `auto-consensus`, `auto-dag-data`, `auto-drive`, `auto-id`, `auto-utils`, and `auto-xdm`.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Bump version in lerna.json to 1.0.5</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 1.0.4 to 1.0.5.
</details>
</td> …
> Bumped version to 1.0.5

- packages/auto-drive/src/api/wrappers.ts
Executing generic file or a simple folder upload from NodeJS an error was thrown because class `[File](https://developer.mozilla.org/en-US/docs/Web/API/File)` was intended to be accessed and is not available in nodejs. 
This occurred on the function `uploadFileFromInput` that received either a `GenericFile` or `File` depending on the `instanceof` I applied some transformations or others. 
I separated `GenericFile` upload and `File` interface upload into `uploadFile` and `uploadFileFromInput`.
___
Bug fix, Enhancement
___
- Refactored the file upload logic to separate handling of `File` and `GenericFile` into distinct functions, `uploadFile` and `uploadFileFromInput`.
- Replaced `uploadFileFromInput` with `uploadFile` in various parts of the code to ensure compatibility with NodeJS.
- …
> Fix File not supported in nodejs

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of all packages from 1.0.5 to 1.0.6.
- Updated dependencies to ensure compatibility with the new version.
- Adjusted Lerna configuration to reflect the new version.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update Lerna configuration version to 1.0.6</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 1.0.5 to 1.0.6.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/169/files#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821">+1/- …
> Publish v1.0.6

- packages/auto-dag-data/package.json
- yarn.lock
___
dependencies
___
- Added `@peculiar/webcrypto` as a dependency in the `package.json` file of the `auto-dag-data` package.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Add @peculiar/webcrypto to dependencies in package.json</code>&nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-dag-data/package.json
- Added `@peculiar/webcrypto` to the dependencies list.
</details>
</td>
<td><a href="https://github.com/autonomys/auto-sdk/pull/174/files#diff-d25a6afb9a68440953980ed158260a4d583b7df0cd040b64c7041e16c9818bbe">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent usage**: Comment …
> Add @peculiar/webcrypto to auto-dag-data

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/jest.config.ts
- packages/auto-dag-data/package.json
- packages/auto-dag-data/src/compression/index.ts
- packages/auto-dag-data/src/encryption/index.ts
- packages/auto-dag-data/src/ipld/chunker.ts
- packages/auto-dag-data/src/ipld/nodes.ts
- packages/auto-dag-data/tests/chunker.spec.ts
- packages/auto-dag-data/tests/compression.spec.ts
- packages/auto-dag-data/tests/encryption.spec.ts
- packages/auto-dag-data/tests/fileRetrievability.spec.ts
- packages/auto-dag-data/tests/nodes.spec.ts
- packages/auto-dag-data/tests/offchainMetadata.spec.ts
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
Adding more testing for: 
- Ensuring file retrievability 
- Cover `processChunksToIPLDFormat` method
___
Tests, Enhancement
___
- Added comprehensive tests for file retrievability, including single and chunked file retrieval, ensuring file integrity.
- Updated versions across multiple packages to maintain consistency and compatibility.
- Adjusted dependencies to align with the new package versions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>fileRetrievability.spec.ts</strong><dd><code>Add tests for file retrievability and chunk processing</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-dag-data/tests/fileRetrievability.spec.ts
<li>Added new test …
> Add more testing to `@autonomys/auto-dag-data` 

- packages/auto-utils/package.json
- yarn.lock
As suggested [here](https://github.com/autonomys/autonomys-agents/pull/21#discussion_r1854402005) thanks @Xm0onh)
___
enhancement, dependencies
___
- Updated the `@polkadot/api` package to version 14.3.1 in `package.json` to address dependency issues.
- This update is intended to fix the dependency chain as suggested in a previous discussion.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update @polkadot/api dependency to version 14.3.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/auto-utils/package.json
<li>Updated <code>@polkadot/api</code> dependency version from …
> Update @polkadot/api to 14.3.1

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
___
enhancement
___
- Updated the version of multiple packages from 1.0.8 to 1.0.9, and from 1.0.7 to 1.0.9 for `auto-xdm`.
- Updated dependencies across packages to ensure compatibility with the new version.
- Updated `gitHead` to reflect the new commit hash for each package.
___
<tr>
<td>
<details>
<summary><strong>lerna.json</strong><dd><code>Update version in Lerna configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lerna.json
- Updated version from 1.0.8 to 1.0.9.
</details>
</td>
<td><a …
> Publish 1.0.9

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish 1.0.11

- packages/auto-utils/src/api.ts
I haven't tested yet if this will automatically switch endpoint if one of them is not working
> Add provider support for multiple endpoints

- packages/auto-dag-data/package.json
- packages/auto-drive/README.md
Updates the doc: 
- Note that this package is intended to be used within a ESM-based application
- Update name in doc from a misnamed function
> Add note for used pkg from ESM application

- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
> Unify package json add missing repository link in auto drive

- packages/auto-drive/package.json
- packages/auto-drive/src/api/wrappers.ts
- packages/auto-drive/tsconfig.json
Using default moduleResolution didn't resolve correctly
> Fix auto-drive tsconfig

- packages/auto-drive/src/api/wrappers.ts
- packages/auto-drive/src/utils/async.ts
Added method for easing the upload of an object as json
> Add upload object as json

- packages/auto-drive/src/api/calls/read.ts
- packages/auto-drive/src/api/models/user.ts
- packages/auto-drive/src/api/wrappers.ts
Added method for querying the current upload/download limits.
> Add get limits method

- README.md
This should fix the issue #215
> chore: update outdated doc

- packages/auto-drive/README.md
Add how to create an API key into the README
> Add how to create an API key into the README

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-id/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish v1.2.4

- README.md
Just adding auto-xdm to the list of packages in root readme
> Add auto-xdm in root readme

- packages/auto-consensus/src/staking.ts
- packages/auto-consensus/src/types/staking.ts
- packages/auto-utils/src/utils/createType.ts
Fix withdrawStake to support multiple withdraw type
> Modify withdraw stake for latest changes

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publishing v1.2.5

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish v1.3.1

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish v1.3.2

- packages/auto-consensus/src/types/extrinsic.ts
- packages/auto-consensus/src/utils/parse.ts
- Fix the method for balances sections
- Improve parsing of the signer
- Improve signature and args typing
> Fix transfers parsing

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish v1.3.3

- packages/auto-drive/src/api/handler.ts
- packages/auto-drive/src/package.ts
- packages/auto-drive/tsconfig.json
Add user agent to api requests for enabling debugging potential issues
> feat: add user agent

- packages/auto-drive/src/api/calls/download.ts
This PR intends to solve the complexity of downloaded files encoding. 
Depends on https://github.com/autonomys/auto-drive/pull/229
> Manage optional encoding

- .vscode/auto.code-workspace
- .vscode/settings.json
- packages/auto-utils/package.json
- yarn.lock
To support Extrinsic V5 (API v15)
> Update Polkadot dependencies

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Publish v1.4.0

- lerna.json
- packages/asynchronous/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- yarn.lock
> Chore: Publish 1.4.2

- packages/auto-drive/README.md
- packages/file-caching/package.json
- packages/file-caching/src/defaultConfigs.ts
- packages/file-caching/src/fileCache.ts
- packages/file-caching/src/index.ts
- packages/file-caching/src/models.ts
- packages/file-caching/src/utils.ts
- packages/file-caching/tsconfig.json
- yarn.lock
Package for managing FS-based file caching with two main default configs:
- Single memory layer 
- Double memory-sqlite3 layer
> File caching package

- packages/auto-utils/__test__/wallet.test.ts
- packages/auto-utils/src/types/wallet.ts
- packages/auto-utils/src/wallet.ts
These ethereum wallet type are essential to perform a domain to consensus XDM for example
> Feat: Add support for creation of ethereum wallet in auto-utils

- lerna.json
- packages/asynchronous/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/file-caching/package.json
- packages/rpc/package.json
- yarn.lock
> Publish v1.4.4

- examples/auto-xdm-transfers/deno.json
- examples/auto-xdm-transfers/deno.lock
- examples/auto-xdm-transfers/main.ts
Add simple deno script to show how to use Auto-XDM package
> Feat: Add auto xdm deno example

- packages/auto-drive/package.json
- packages/auto-drive/src/browser.ts
- packages/auto-drive/src/offline/cid.ts
- packages/auto-drive/src/offline/index.ts
- yarn.lock
Wrap into async methods some useful tools in `@autonomys/auto-dag-data`
> feat: add auto-dag-data methods

- lerna.json
- packages/asynchronous/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-drive/src/offline/cid.ts
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/file-caching/package.json
- packages/rpc/package.json
- yarn.lock
CID should be a string for being able to manipulate correctly w/o using `@autonomys/auto-data-data`.
I also added a method for getting the CID (string formatted) from the blake3 hash
> Fix cid format

- packages/rpc/src/rpc/api/index.ts
- packages/rpc/src/rpc/index.ts
I missed to export the changes at #327
> fix: missing export in api typings

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/__test__/rpc/typed.spec.ts
- packages/utility/rpc/__test__/ws/client.spec.ts
- packages/utility/rpc/__test__/ws/server.spec.ts
- packages/utility/rpc/package.json
- packages/utility/rpc/src/rpc/client.ts
- packages/utility/rpc/src/ws/client.ts
- packages/utility/user-session/package.json
- yarn.lock
The naming in callbacks was confusing since `onOpen` was triggered in every open. I updated them to three callbacks:
- `onEveryOpen`
- `onFirstOpen`
- `onReconnection`
> Update callback naming

- lerna.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
> Chore: Publish 1.4.17

- packages/auto-mcp-servers/README.md
- packages/auto-mcp-servers/package.json
- packages/auto-mcp-servers/src/auto-drive/index.ts
- packages/auto-mcp-servers/src/bin/auto-drive.ts
- packages/auto-mcp-servers/src/index.ts
- packages/auto-mcp-servers/tsconfig.json
- yarn.lock
This pull request introduces a new package, `@autonomys/auto-mcp-servers`, which provides Model Context Protocol (MCP) servers for Autonomys services. The initial implementation includes an "Auto Drive Server" that exposes functionality from the `@autonomys/auto-drive` package as MCP tools. The most important changes include adding the server's implementation, configuration, and usage documentation.
* [`packages/auto-mcp-servers/src/auto-drive/index.ts`](diffhunk://#diff-9a1193dc1e5a41ac74c22ff09258e1be843dff916f0523517872bd9b1fe4caa9R1-R41): Implemented the "Auto Drive Server" with an `uploadObject` tool to upload JSON objects to the Autonomys network. The tool supports optional encryption via an environment variable (`ENCRYPTION_PASSWORD`).
* …
> Add auto-mcp-servers package

- packages/auto-agents/README.md
- packages/auto-agents/jest.config.js
- packages/auto-agents/package.json
- packages/auto-agents/src/experiences/__tests__/cidManager.test.ts
- packages/auto-agents/src/experiences/abi/memory.ts
- packages/auto-agents/src/experiences/cidManager.ts
- packages/auto-agents/src/experiences/experienceManager.ts
- packages/auto-agents/src/experiences/experienceStorage.ts
- packages/auto-agents/src/experiences/index.ts
- packages/auto-agents/src/experiences/storage.ts
- packages/auto-agents/src/experiences/types.ts
- packages/auto-agents/src/experiences/utils.ts
- packages/auto-agents/src/index.ts
- packages/auto-agents/tsconfig.json
- yarn.lock
This pull request introduces the initial implementation of the `@autonomys/auto-agents` SDK, which provides tools for managing autonomous agent states ("experiences") on the Autonomys Network. The changes include the core features, configuration setup, and supporting utilities for saving, retrieving, and managing agent experiences both locally and on-chain.
The reason to move this out of the [autonomys-agents](https://github.com/autonomys/autonomys-agents) repo is to facilitate easier re-use with other frameworks and via MCP.
* **README Documentation**: Added comprehensive documentation (`README.md`) covering the SDK's features, installation, usage examples, and contact information. This includes details on saving and retrieving agent experiences, on-chain state tracking, and local …
> Add auto-agents package

- packages/utility/file-caching/src/models.ts
- packages/utility/file-caching/src/utils.ts
Updating file response data from AsyncIterable to Stream to improve the controllability of the file download
> update: file response model

- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-drive/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
Includes v1.4.19: https://github.com/autonomys/auto-sdk/pull/384
Includes v1.4.20: https://github.com/autonomys/auto-sdk/pull/385
> Chore 1.4.20

- packages/utility/asynchronous/src/concurrency/weightedRequestsConcurrencyController.ts
Solves the issue discovered [here](https://github.com/autonomys/auto-files-gateway/pull/92)
> Add validation to `weightedRequestConcurrencyController`

- packages/utility/file-caching/src/models.ts
- packages/utility/file-caching/src/utils.ts
`Stream` was not the correct class to use but `Readable` since it a Stream could be not readable but obviously file streams should be readable.
> fix: stream handling

- .gitignore
- packages/auto-design-system/.babelrc
- packages/auto-design-system/.storybook/main.js
- packages/auto-design-system/.storybook/postcss.config.js
- packages/auto-design-system/.storybook/preview.js
- packages/auto-design-system/.storybook/webpack.config.js
- packages/auto-design-system/README.md
- packages/auto-design-system/package.json
- packages/auto-design-system/postcss.config.js
- packages/auto-design-system/rollup.config.js
- packages/auto-design-system/src/Introduction.mdx
- packages/auto-design-system/src/components/Button/Button.stories.tsx
- packages/auto-design-system/src/components/Button/index.tsx
- packages/auto-design-system/src/components/Dropdown/Dropdown.stories.tsx
- packages/auto-design-system/src/components/Dropdown/index.tsx
- packages/auto-design-system/src/index.ts
- packages/auto-design-system/src/styles.css
- packages/auto-design-system/src/tokens/DesignTokensColors.stories.tsx
- packages/auto-design-system/src/tokens/DesignTokensShadows.stories.tsx
- packages/auto-design-system/src/tokens/DesignTokensSpacing.stories.tsx
- packages/auto-design-system/src/tokens/DesignTokensTypography.stories.tsx
- packages/auto-design-system/tailwind.config.js
- packages/auto-design-system/tsconfig.json
- yarn.lock
`@autonomys/auto-design-system` with improved styling and accessibility
Enhances our `React component library` with consistent styling from `@autonomys/design-tokens`, improved accessibility compliance, and expanded component documentation in `Storybook`.
> feat: ✨  add auto-design-system sdk

- .github/workflows/release.yaml
- .husky/commit-msg
- .husky/pre-commit
- RELEASE.md
- commitlint.config.js
- package.json
- scripts/generate-pr-changelog.js
- scripts/setup-github-token.sh
- yarn.lock
This PR establishes a standardized release cycle with automated changelog generation based on PRs, streamlining version management across the SDK packages.
- PR-based changelog generator that categorizes and credits contributions
- Automated release workflow with version bumping (patch/minor/major)
- Commit message validation with commitlint
- Simplified release commands and documentation
- Synchronized versioning across all packages
Apply to CHANGELOG.md
```bash
BUMP_TYPE=minor yarn changelog
yarn lerna version minor
```
--------------------------------
Or use the GitHub Action for fully automated releases, which handles changelog generation, version bumping, npm publishing, and GitHub release creation in one workflow.
> feat(workflow): ✨ add release cycle and changelog

- .github/workflows/pr-title-check.yaml
- .husky/commit-msg
- .husky/pre-commit
- RELEASE.md
- package.json
- scripts/generate-pr-changelog.js
- yarn.lock
- This removes the friction, from the commit message, @marc-aurele-besner has addressed, the commit will only check the commit message correct convention meaning, will need to add the `pre-fix` like `feat: , fix: , chore: etc` always to let other people know what this commit is about.
- when the PR is create PR should also follow the github commit convention.
> fix: 🐛 remove lint and format check and have PR title check on the work flow

- packages/utility/asynchronous/package.json
- packages/utility/asynchronous/src/index.ts
- packages/utility/asynchronous/src/streams/index.ts
- yarn.lock
Was already approved but merge into closed PR
> feat: safe fork stream method for asynchronous pkg

- .github/workflows/release.yaml
- CHANGELOG.md
- examples/auto-drive-create-next-app/package.json
- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-design-system/package.json
- packages/auto-drive/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/design-tokens/package.json
- packages/utility/file-caching/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
Add `ref: ${{ github.ref }}` to checkout step for ensuring refreshing every time it executes.
> chore: v1.4.32

- packages/auto-drive/src/api/calls/download.ts
- packages/auto-drive/src/api/models/asyncDownloads.ts
- packages/auto-drive/src/api/types.ts
- packages/auto-drive/src/api/wrappers.ts
Add async downloads tools for auto-drive sdk
> feat: ✨ add async download functionality to AutoDrive API

- .github/CODEOWNERS
> chore: remove Marc-Aurele from codeowners file

- packages/utility/asynchronous/src/streams/index.ts
Added method for converting a stream into a buffer
> feat: add `streamToBuffer` method

- packages/utility/rpc/src/rpc/api/definition.ts
- packages/utility/rpc/src/rpc/api/index.ts
- packages/utility/rpc/src/rpc/api/testing.ts
- packages/utility/rpc/src/rpc/api/typing.ts
- packages/utility/rpc/src/rpc/server.ts
- packages/utility/rpc/src/rpc/types.ts
This PR adds some utils for creating a mock server client for enabling integrations testing
> feat(@autonomys/rpc): add utils for testing rpc integrations

- packages/auto-drive/README.md
- packages/auto-drive/src/api/calls/read.ts
- packages/auto-drive/src/api/calls/write.ts
- packages/auto-drive/src/api/types.ts
- packages/auto-drive/src/api/wrappers.ts
This PR adds methods for handling auto-dri ve moderation programatically
> feat: add report features to auto-drive pkg

- CHANGELOG.md
- examples/auto-drive-create-next-app/package.json
- examples/next/package-lock.json
- examples/next/package.json
- examples/node/package.json
- lerna.json
- packages/auto-agents/package.json
- packages/auto-consensus/package.json
- packages/auto-dag-data/package.json
- packages/auto-design-system/package.json
- packages/auto-drive/package.json
- packages/auto-files/package.json
- packages/auto-mcp-servers/package.json
- packages/auto-utils/package.json
- packages/auto-xdm/package.json
- packages/utility/asynchronous/package.json
- packages/utility/contracts/package.json
- packages/utility/design-tokens/package.json
- packages/utility/file-server/package.json
- packages/utility/rpc/package.json
- packages/utility/user-session/package.json
- yarn.lock
This pull request prepares the release for version `1.5.15` across the monorepo, updating package versions and dependencies, and updating the changelog to document new features and bug fixes.
> chore: v1.5.15
